apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
      version: blue
  template:
    metadata:
      labels:
        app: appointment-service
        version: blue
    spec:
      containers:
      - name: appointment-service
        image: registry.digitalocean.com/healthsynccontainer/appointment-service:blue
        ports:
        - containerPort: 80
        env:
        - name: AWS_REGION
          value: "ap-southeast-1"  # DynamoDB region (adjust to your region)
        - name: DYNAMODB_TABLE_NAME
          value: "appointments"  # DynamoDB table name for appointments
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-blue
spec:
  selector:
    app: appointment-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: ClusterIP
