apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVI3MlBIRFBLSU5KRUxQNFM=
  AWS_SECRET_ACCESS_KEY: MGE2T1VLb1BGb3RaQ3ZXamp2T3doOUJkTGhPdmJkK2YvbnlmelRMZg==
