apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
      version: blue
  template:
    metadata:
      labels:
        app: patient-service
        version: blue

    spec:
      containers:
      - name: patient-service
        image: registry.digitalocean.com/healthsynccontainer/patient-service:blue
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "healthsync-db.cfiqoygw47no.ap-southeast-1.rds.amazonaws.com"
        - name: DB_USER
          value: "tharinduMaheesha"
        - name: DB_PASSWORD
          value: "Robertpwd3789"
        - name: DB_NAME
          value: "healthsync"
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: patient-service-blue
spec:
  selector:
    app: patient-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
