apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      version: blue
  template:
    metadata:
      labels:
        app: notification-service
        version: blue
    spec:
      containers:
      - name: notification-service
        image: registry.digitalocean.com/healthsynccontainer/notification-service:blue
        ports:
        - containerPort: 80
        env:
        - name: AWS_REGION
          value: "ap-southeast-1"  # DynamoDB region (adjust to your region)
        - name: DYNAMODB_TABLE_NAME
          value: "appointments"  # DynamoDB table name for notifications
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: DB_HOST
          value: "healthsync-db.cfiqoygw47no.ap-southeast-1.rds.amazonaws.com"
        - name: DB_USER
          value: "tharinduMaheesha"
        - name: DB_PASSWORD
          value: "Robertpwd3789"
        - name: DB_NAME
          value: "healthsync"
      imagePullSecrets:
      - name: do-secret

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-blue
spec:
  selector:
    app: notification-service
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003
  type: ClusterIP
