name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Python and dependencies for testing
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies for patient service
        working-directory: ./patient-record-service
        run: |
          pip install -r requirements.txt

      - name: Run unit tests for patient service
        working-directory: ./patient-record-service
        run: pytest tests --maxfail=1 --disable-warnings

      # Log in to DigitalOcean container registry
      - name: Log in to DigitalOcean
        run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

      # Build and push each service
      - name: Build and push service1
        run: |
          docker build -t registry.digitalocean.com/healthsynccontainer/patient-service ./patient-record-service
          docker push registry.digitalocean.com/healthsynccontainer/patient-service

      - name: Build and push service2
        run: |
          docker build -t registry.digitalocean.com/healthsynccontainer/doctor-service ./doctor-record-service
          docker push registry.digitalocean.com/healthsynccontainer/doctor-service

      - name: Build and push service3
        run: |
          docker build -t registry.digitalocean.com/healthsynccontainer/appointment-service ./appointment-service
          docker push registry.digitalocean.com/healthsynccontainer/appointment-service

      - name: Build and push service4
        run: |
          docker build -t registry.digitalocean.com/healthsynccontainer/notification-service ./notification-service
          docker push registry.digitalocean.com/healthsynccontainer/notification-service

  deploy:
    needs: build-and-push  # Ensures that deployment happens only after the build job succeeds
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-1-31-1-do-5-sgp1-1734158660661

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/aws-secrets.yaml
        kubectl apply -f k8s/appointment-service-deployment.yaml
        kubectl apply -f k8s/doctor-service-deployment.yaml
        kubectl apply -f k8s/notification-service-deployment.yaml
        kubectl apply -f k8s/patient-service-deployment.yaml
        kubectl apply -f k8s/ingress.yaml
