name: Deploy to DO Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-1-31-1-do-5-sgp1-1734158660661

    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f k8s/appointment-service-deployment.yaml
        kubectl apply -f k8s/doctor-service-deployment.yaml
        kubectl apply -f k8s/notification-service-deployment.yaml
        kubectl apply -f k8s/patient-service-deployment.yaml
        kubectl apply -f k8s/aws-secrets.yaml
        kubectl apply -f k8s/ingress.yaml
